### ISSUE TITLE
Nightly support release checklist

### ISSUE THREAD

**Issue by wizzomafizzo** [wizzomafizzo/starcheat#282]
- [ ] py-starbound support for new database format (SBBF04?)
- [ ] Graphic glitches, countless ones showing up now (see Avian species for example)
- [ ] Crash when opening ship dialog, possibly to do with new character: #271
- [ ] Blueprint dialog crash if null value in list: #260 
- [ ] Quests dialog completely broken, need support for new format

Less important:
- [ ] Weapon generation is completely broken (see [here](https://dev.sulphur-hosting.net/) for some inspiration)
- [ ] Blueprint list reordering on modification: #249 
- [ ] Support for more directives: #261

**Comment by wizzomafizzo** [comment]
Starfuse by @Qix- is a potential alternative to py-starbound. Will be testing soon

**Comment by wizzomafizzo** [comment]
Graphic glitches may have something to do with the background of the labels? Need to do some more testing but a lot of stuff magically fixed itself when I randomly changed the background colour

**Comment by wizzomafizzo** [comment]
@chrmoritz just fyi i think we will end up using starfuse instead of py-starbound (minus the fuse parts). qix is taking a look at the new format in nightly soon, blixt has said he has no time to work on the project at the moment

**Comment by Qix-** [comment]
Happy to look at it. Any information you have about it will definitely help, too.

**Comment by wizzomafizzo** [comment]
Shoot man I'll gladly do anything I can to help! I'm not sure what would be helpful though, happy to hear anything you think you need

**Comment by wizzomafizzo** [comment]
Don't feel like I'm dobbing you in either :P no rush on this stuff

**Comment by Qix-** [comment]
Well first off, have you tried just adding the `SBBF04` string into the array that's checked in the header check for existing libs to see if 'just works'? I'm wondering how much of a change warrants the version number increase or if that's just a way to enforce certain asset files be used with certain versions. I can't imagine the devs changing a simple block format so much between versions, and `SBBF03` works just fine with the `SBBF02` version.

**Comment by wizzomafizzo** [comment]
I did but no dice. The new string at least for vanilla assets file is "SBAsset4". It might be as simple as making the string longer than 6 bytes but I wasn't sure if that would break things. 

Btw I need to make it work with Python 3 too but I can always fork it and make the changes myself if it can't work for both like py-starbound. As far as I got all I had to do was make the module imports case sensitive and explicitly make some regular strings byte strings. That doesn't really matter for now but just a heads up

**Comment by Qix-** [comment]
Gotcha, I can make that a priority for you :)

**Comment by medeor413** [comment]
The nightly SBAsset4 format appears to be very different from the old SBBF03 format. I spent a while trying to figure it out, and this is what I came up with:

At the beginning of the file, magic bytes "SBAsset4"
8 bytes immediately following, offset of file index
Following that, apparently unmodified files (.. replaces newline)
At offset specified in beginning of file (end of files), magic bytes "INDEX"
32 mystery bytes after INDEX (empty in modpaks)
1 byte with length of pak name
Name of pak (ex. "Main Game Assets - 04 Jul 2016")
Variable number of mystery bytes (related to number of files)
File index format:
Byte with length of path
Complete file path
8 bytes containing offset of file
8 bytes containing length of file
File ends without any sort of marker

**Comment by Xirukai** [comment]
1.0 is out on the unstable branch. Just giving a friendly headsup, using this program tons ;)

**Comment by chrmoritz** [comment]
And the [release date for stable](http://playstarbound.com/starbound-release-announcement/) is the **22 July.** 🎉 

cc @wizzomafizzo

**Comment by medeor413** [comment]
I've got a fork that can read Cheerful player files, but it's mostly useless without something to read SBAsset4, and unfortunately I think that writing something for that is beyond my skills.

**Comment by Qix-** [comment]
Thanks @medeor413 I can play with it sometime next weekend probably and try it out with `starfuse`.

**Comment by wizzomafizzo** [comment]
oops well i guess people are gonna have to chill out and wait a while

@medeor413 are you saying this release changed the player files too? that's a bummer

**Comment by medeor413** [comment]
I've already got a fork that works with 1.0 player files, and I started working on something to work with SBAsset, but I'm stuck there.

**Comment by wizzomafizzo** [comment]
@medeor413 i think the fork looks good i'd be happy to take pull requests if you like

we have to wait for a really nice person to do it :P i'm stuck too

**Comment by medeor413** [comment]
I'll put in a PR once I get SBAsset working, since it'll be pretty useless without it.

**Comment by medeor413** [comment]
Aaand done. [Pull request here.](https://github.com/wizzomafizzo/starcheat/pull/288)

**Comment by chrmoritz** [comment]
As Windows nightly build of this PR is available here: https://ci.appveyor.com/project/wizzomafizzo/starcheat/build/master-b48/job/x20vc56bjy89k32l/artifacts (if anyone else wants to try it out without having to compile the sources).

**Comment by wizzomafizzo** [comment]
dude you rock, i'm sure you just made a lot of people happy. i will give it a shot when i get home

have you noticed much difference between this implementation and py-starbound? i just wonder if it got noticeably slower

**Comment by medeor413** [comment]
It takes a while for me, but my loading times have always been long due to sheer size of my player files.

**Comment by wizzomafizzo** [comment]
All good. Hey I'll have to leave this one a bit longer I think, I have no internet atm and can't test anything. If you wanna make changes or have suggestions or whatever don't hold back too, I'm up for whatever

Btw would you be able to upload a screenshot of how it looks now with the UI changes you made? Interested to see them too

**Comment by wizzomafizzo** [comment]
I wonder if there is a way to speed up the player file loading too? I haven't looked at it in a while but from memory the biggest bottleneck is simply loading up the inventory icons from disk. I'm not sure if it's really avoidable

**Comment by kurisubrooks** [comment]
Here's how it currently looks. Pillow has some rendering issues, Description and Mouse slots are pending removal, and the hotbar is not currently functional, but the overall function is there.

![image](https://cloud.githubusercontent.com/assets/6291467/17134337/402cc9a8-536d-11e6-85fc-90a0f2ec6341.png)

**Comment by kurisubrooks** [comment]
I just tested loading Starcheat 0.27 and pending 1.0 release, but to me 1.0 seems faster.
0.27 was tested on my laptop however (OS X) and 1.0 on my Desktop (Windows 10)

Overall I don't think there is much of a difference.

**Comment by kurisubrooks** [comment]
You can see all current issues here: https://github.com/medeor413/starcheat/issues

**Comment by wizzomafizzo** [comment]
btw i still have no internet connection at home sorry guys. @chrmoritz if you are comfortable with doing a release at some point please go ahead but i'm ok with waiting until i can test it myself

**Comment by wizzomafizzo** [comment]
hey could someone give me a run down of where this is at? not sure i'm keeping up. should we be doing a new release?

@chrmoritz could you please help with your git expertise again too i don't know how i would merge the pull request and make dev sync with master

**Comment by blixt** [comment]
Not sure if you need this anymore, but I've updated py-starbound now to support all the Starbound 1.0 file formats, including write support for SBVJ01 files that's relatively fast (a `.player` file that's 128 kB writes in 0.029 seconds for me):

```python
import starbound, time
start = time.clock()
with open('SB/storage/player/916d5878483e3a40d10467dc419982c2.player', 'rb') as fh:
  vj = starbound.read_sbvj01(fh)

print('Took %s seconds to read file' % (time.clock() - start,))
print('Player name: %s' % (vj.data['identity']['name'],))

start = time.clock()
with open('SB/storage/player/916d5878483e3a40d10467dc419982c2.player.dupe', 'wb') as fh:
  starbound.write_sbvj01(fh, vj)

print('Took %s seconds to write file' % (time.clock() - start,))
```

You may also get better speed by using the `mmap` package.

**Comment by blixt** [comment]
Oh I misunderstood the bottleneck, for SBAsset6 files you should definitely use `mmap` for better performance. The `export.py` script in py-starbound extracts all 44,692 files in `packed.pak` (892 MB) in 8 seconds for me (compared to Starbound's own `asset_unpacker` which takes over 10 seconds).

**Comment by kurisubrooks** [comment]
@medeor413 wanna take a look into this?

**Comment by Qix-** [comment]
@blixt:
> for SBAsset6 files you should definitely use mmap for better performance

I'm sorry I haven't been very active in the SB community lately (full time job took over my life) but my implementation of the SBAsset3 format uses `mmap` in Python if anyone wants a reference.

**Comment by blixt** [comment]
@Qix- Ah, great. See below for how I'm currently using `mmap`, and let me know if there are potential improvements to how to configure `mmap`!

```python
import mmap, starbound
with open('SB/assets/packed.pak', 'rb') as fh:
  mm = mmap.mmap(fh.fileno(), 0, access=mmap.ACCESS_READ)
  package = starbound.SBAsset6(mm)
  print(package.get('/lighting.config'))
```

**Comment by Qix-** [comment]
I'm not sure exactly what Python does under the hood to manage mmap calls, but I know that I gained noticeable performance increases by only mmap'ing the blocks that needed read (the first time they were read, of course) and making sure to map a multiple of `mmap.PAGESIZE` bytes at a  time, starting at offsets of multiples of `mmap.PAGESIZE` for alignment boosts, which allow reads to be quicker. IIRC the assets file format has a "rounded" block size which helped out with this as well (the pages were an exponent of 2, which helped alignment a bit).

**Comment by Malenenshadow** [comment]
im having issues with starcheat since today... every time i start it up it stops responding. after five minutes its still like that so im not sure whats wrong since its not giving me an error report

**Comment by Malenenshadow** [comment]
Update: so it is loading up. but its SUUUUUUUUUUUUUUUPER slow

**Comment by blixt** [comment]
Do you have the file that's slow? Also I would create a separate issue
since it seems to load in the end

**Comment by WInf9Kieran** [comment]
```
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 86, in <module>
  File "build\starcheat.py", line 83, in main
  File "build\gui\mainwindow.py", line 154, in __init__
  File "build\gui\utils.py", line 103, in check_index_valid
  File "build\gui\utils.py", line 64, in build_assets_db
  File "build\assets\core.py", line 127, in find_assets
  File "build\assets\core.py", line 156, in scan_asset_folder
  File "build\starbound\helpers.py", line 213, in open
  File "build\starbound\helpers.py", line 220, in read_stream
  File "build\starbound\btreedb4.py", line 119, in initialize
  File "build\starbound\sbbf02.py", line 89, in initialize
AssertionError: Invalid file format
```

this is the error. I am trying to convert my old gamesave to the new update. I downloaded this starcheat verison: starcheat-5b0e5ff-win32
I have the newest starbound verison. Is starcheat for 1.0 currently broken?

**Comment by kurisubrooks** [comment]
Starcheat 1.0 can only open Starbound 1.0 player files. 
The 2 player file types are incompatible with each other. 

Use an older version of Starcheat to access your older player files, export any custom items or weapons you may want to keep, then import then into a new 1.0 player file.

**Comment by WInf9Kieran** [comment]
Thats what I did. I imported it correctly but thats not the problem. Starcheat crashes when I start it. Cant even load a player. Also, my player folders are empty. Both in the old starbound and new.

**Comment by kurisubrooks** [comment]
That crash log appears to be from an older version of Starcheat. 
Please use this version, as it is the latest build.

https://ci.appveyor.com/api/buildjobs/mj9h9ri0cxdgfabc/artifacts/dist%2Fstarcheat-9d543cd-win64.zip

**Comment by kurisubrooks** [comment]
Might I also ask where you found the build that you are currently using? We get so many issues from users using this old build, and it is frankly pissing me off. Was it posted somewhere online?

**Comment by WInf9Kieran** [comment]
I followed the steps that is on here. https://github.com/wizzomafizzo/starcheat clicked on TBD - nightly builds available, then the first url, there i clicked the first job name https://ci.appveyor.com/project/wizzomafizzo/starcheat/branch/dev and went to artifacts where i downloaded the zip

**Comment by kurisubrooks** [comment]
The dev branch is not maintained for 1.0 builds, it's only up-to-date for Starbound Beta, 1.0 is maintained in a separate repository. @wizzomafizzo @chrmoritz Could we please add another link to the README for 1.0 builds?

**Comment by WInf9Kieran** [comment]
oh okay. Well its something. But is it normal that it takes so long to update the item slots? It's stuck at 0% after I imported the json :/

**Comment by kurisubrooks** [comment]
Some people are still having trouble with load times, which is why the beta builds haven't hit stable yet. The rest of the 1.0 features are there, but we can't figure out the load times. We've narrowed it down to having to do with HDD speeds, but we're trying to circumvent this.

**Comment by WInf9Kieran** [comment]
So I just gotta wait, right?

Well thank you very much for all the help anyways!

**Comment by wulfgren** [comment]
Is there a link somewhere to the newest version? I've been looking around for it so I can toy add some materials I'm too lazy to farm. I tried the link provided above and it crashes with my all my saves even brand new ones. Feel free to tell me I'm dumb and doing it wrong.
this is the log.
Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 86, in <module>
  File "build\starcheat.py", line 83, in main
  File "build\gui\mainwindow.py", line 179, in __init__
  File "build\gui\mainwindow.py", line 556, in open_file
  File "build\gui\mainwindow.py", line 206, in update
  File "build\saves.py", line 565, in get_pixels
KeyError: 'money'

**Comment by Rensay** [comment]
dose the nightly currently not work with mod races?

**Comment by Untuned** [comment]
Latest nightly build:

> Traceback (most recent call last):
>   File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
>   File "build\starcheat.py", line 86, in <module>
>   File "build\starcheat.py", line 83, in main
>   File "build\gui\mainwindow.py", line 179, in __init__
>   File "build\gui\mainwindow.py", line 556, in open_file
>   File "build\gui\mainwindow.py", line 206, in update
>   File "build\saves.py", line 565, in get_pixels
> KeyError: 'money'

**Comment by OfficialMuffin** [comment]
I'm getting these errors. I'm running Starbound version 1.4

> Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "build\starcheat.py", line 83, in <module>
  File "build\starcheat.py", line 80, in main
  File "build\gui\mainwindow.py", line 154, in __init__
  File "build\gui\utils.py", line 103, in check_index_valid
  File "build\gui\utils.py", line 64, in build_assets_db
  File "build\assets\core.py", line 127, in find_assets
  File "build\assets\core.py", line 156, in scan_asset_folder
  File "build\starbound\helpers.py", line 213, in open
  File "build\starbound\helpers.py", line 220, in read_stream
  File "build\starbound\btreedb4.py", line 119, in initialize
  File "build\starbound\sbbf02.py", line 89, in initialize
AssertionError: Invalid file format

**Comment by chrmoritz** [comment]
@OfficialMuffin You're probably using starcheat 0.27.1, which was the latest stable starcheat version compatible with the Starbound version pre Starbound 1.0.

There is a beta starcheat version with Starbound 1.0+ support available here: https://github.com/wizzomafizzo/starcheat/releases/tag/beta-v1
But support for Starbound 1.0+ is still incomplete as this project is unfortunately no longer actively maintained.

**Comment by OfficialMuffin** [comment]
Ah I see,

Thanks, I'll check it out.

On 28 Jun 2019 22:30, Christian Moritz <notifications@github.com> wrote:

@OfficialMuffin<https://github.com/OfficialMuffin> You're probably using starcheat 0.27.1, which was the latest stable starcheat version compatible with the Starbound version pre Starbound 1.0.

There is a beta starcheat version with Starbound 1.0+ support available here: https://github.com/wizzomafizzo/starcheat/releases/tag/beta-v1
But support for Starbound 1.0+ is still incomplete as this project is unfortunately no longer actively maintained.
